version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    depends_on:
      - backend
